# Generated by Django 6.0.3 on 2026-03-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('codigo', models.TextField(blank=True, null=True)),
                ('uf', models.TextField(blank=True, null=True)),
                ('ra', models.TextField(blank=True, null=True)),
                ('uf_ra', models.TextField(blank=True, null=True)),
                ('resultado', models.FloatField(blank=True, null=True)),
                ('resultado_com_dg', models.FloatField(blank=True, null=True)),
                ('rla', models.FloatField(blank=True, null=True)),
                ('desp_adm_total', models.FloatField(blank=True, null=True)),
                ('alugueis', models.FloatField(blank=True, null=True)),
                ('custo_ocupacao', models.FloatField(blank=True, null=True)),
                ('producao_total', models.FloatField(blank=True, null=True)),
                ('atendimento_total', models.IntegerField(blank=True, null=True)),
                ('caixa_total', models.IntegerField(blank=True, null=True)),
                ('gerencia_total', models.IntegerField(blank=True, null=True)),
                ('atendimento_col', models.IntegerField(blank=True, null=True)),
                ('dea', models.FloatField(blank=True, null=True)),
                ('clientes', models.IntegerField(blank=True, null=True)),
                ('gerentes', models.IntegerField(blank=True, null=True)),
                ('receita_colab', models.FloatField(blank=True, null=True)),
                ('custo_atendimento', models.FloatField(blank=True, null=True)),
                ('pct_caixa', models.FloatField(blank=True, null=True)),
                ('metas_media', models.FloatField(blank=True, null=True)),
                ('metas_1s24', models.FloatField(blank=True, null=True)),
                ('metas_2s24', models.FloatField(blank=True, null=True)),
                ('metas_1s25', models.FloatField(blank=True, null=True)),
                ('metas_2s25', models.FloatField(blank=True, null=True)),
                ('data_abertura', models.TextField(blank=True, null=True)),
                ('alta_ma', models.IntegerField(blank=True, null=True)),
                ('media_alta_ma', models.IntegerField(blank=True, null=True)),
                ('media_ma', models.IntegerField(blank=True, null=True)),
                ('baixa_ma', models.IntegerField(blank=True, null=True)),
                ('middle', models.IntegerField(blank=True, null=True)),
                ('empresarial', models.IntegerField(blank=True, null=True)),
                ('empresas', models.IntegerField(blank=True, null=True)),
                ('empreendedor', models.IntegerField(blank=True, null=True)),
                ('consignado', models.FloatField(blank=True, null=True)),
                ('imobiliario', models.FloatField(blank=True, null=True)),
                ('parcelado_pf', models.FloatField(blank=True, null=True)),
                ('parcelado_pj', models.FloatField(blank=True, null=True)),
                ('plano_empresario', models.FloatField(blank=True, null=True)),
                ('rotativo_pf', models.FloatField(blank=True, null=True)),
                ('rotativo_pj', models.FloatField(blank=True, null=True)),
                ('agro', models.FloatField(blank=True, null=True)),
                ('taxa_conversao', models.TextField(blank=True, null=True)),
                ('novo_modelo', models.TextField(blank=True, null=True)),
                ('encerramento', models.TextField(blank=True, null=True)),
                ('qt_contratos', models.IntegerField(blank=True, null=True)),
                ('vl_producao_visita', models.FloatField(blank=True, null=True)),
                ('nr_portabilidade', models.IntegerField(blank=True, null=True)),
                ('vl_seguros_total', models.FloatField(blank=True, null=True)),
                ('tipologia', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('metragem_quadrada', models.IntegerField(blank=True, null=True)),
                ('superintendencia', models.TextField(blank=True, null=True)),
                ('porte', models.IntegerField(blank=True, null=True)),
                ('horario_funcionamento', models.TextField(blank=True, null=True)),
                ('dentro_orgao', models.BooleanField(default=False)),
                ('escriturarios', models.IntegerField(blank=True, null=True)),
                ('gerente_negocio', models.IntegerField(blank=True, null=True)),
                ('gerente_expediente', models.IntegerField(blank=True, null=True)),
                ('gerente_geral', models.IntegerField(blank=True, null=True)),
                ('caixa_bancario', models.IntegerField(blank=True, null=True)),
                ('demais_cargos', models.IntegerField(blank=True, null=True)),
                ('qt_contratos_visita', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidades',
                'ordering': ['id'],
            },
        ),
    ]
