-- GECAN SQLite schema — extend with new tables as needed.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS unidades (
  id INTEGER PRIMARY KEY,
  nome TEXT NOT NULL,
  codigo TEXT,
  uf TEXT,
  ra TEXT,
  uf_ra TEXT,
  resultado REAL,
  resultado_com_dg REAL,
  rla REAL,
  desp_adm_total REAL,
  alugueis REAL,
  custo_ocupacao REAL,
  producao_total REAL,
  atendimento_total INTEGER,
  caixa_total INTEGER,
  gerencia_total INTEGER,
  atendimento_col INTEGER,
  dea REAL,
  clientes INTEGER,
  gerentes INTEGER,
  receita_colab REAL,
  custo_atendimento REAL,
  pct_caixa REAL,
  metas_media REAL,
  metas_1s24 REAL,
  metas_2s24 REAL,
  metas_1s25 REAL,
  metas_2s25 REAL,
  data_abertura TEXT,
  alta_ma INTEGER,
  media_alta_ma INTEGER,
  media_ma INTEGER,
  baixa_ma INTEGER,
  middle INTEGER,
  empresarial INTEGER,
  empresas INTEGER,
  empreendedor INTEGER,
  consignado REAL,
  imobiliario REAL,
  parcelado_pf REAL,
  parcelado_pj REAL,
  plano_empresario REAL,
  rotativo_pf REAL,
  rotativo_pj REAL,
  agro REAL,
  taxa_conversao TEXT,
  novo_modelo TEXT,
  encerramento TEXT,
  qt_contratos INTEGER,
  vl_producao_visita REAL,
  nr_portabilidade INTEGER,
  vl_seguros_total REAL,
  tipologia TEXT,
  endereco TEXT,
  metragem_quadrada INTEGER,
  superintendencia TEXT,
  porte INTEGER,
  horario_funcionamento TEXT,
  dentro_orgao INTEGER NOT NULL DEFAULT 0,
  escriturarios INTEGER,
  gerente_negocio INTEGER,
  gerente_expediente INTEGER,
  gerente_geral INTEGER,
  caixa_bancario INTEGER,
  demais_cargos INTEGER,
  qt_contratos_visita INTEGER
);

-- Placeholder for app-wide key/value or future reference tables.
CREATE TABLE IF NOT EXISTS meta (
  key TEXT PRIMARY KEY,
  value TEXT
);
